stages:
  make_dataset:
    cmd: python /src/data/make_dataset.py
    deps:
      - /data/raw/creditcard.csv
      - /src/data/make_dataset.py
    params:
      - make_dataset.test_split
      - make_dataset.seed
    outs:
      - ./data/processed/

  train_model:
    cmd: python /src/models/train_model.py  data/processed/train.csv
    deps:
      - data/processed/train.csv
      - /src/models/train_model.py
    params:
      - train_model.n_estimators
      - train_model.max_depth
      - train_model.seed
    outs:
      - models
