# .github/workflows/ci_cd.yml
name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main file
        run: |
          python src/data/make_dataset.py

      - name: Run main file
        run: |
          python src/models/train_model.py

      - name: Run main file
        run: |
          python src/visualization/visualize.py
